<?php

use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use \Drupal\redirect\Entity\Redirect;
use \Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use \Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RedirectResponse;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_help().
 */
function drusign_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.drusign':
      return t('<p>The "Drusign" Module provides Contract Signing Capabilities for Drupal</p>');
  }
}

/**
 * Implements hook_mail().
 */
function drusign_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];
  switch ($key) {
    case 'drusign_send_contract':
      $contractUrl = $params["contractUrl"];
      $receiverName = $params["receiverName"];
      $senderName = $params["senderName"];

      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t("Important Contract from {$senderName}", [], $options);
      $message['body'][] = t("Dear Mr, Mrs {$receiverName},<br/>there is a Contract from {$senderName} for you to sign.<br/> Please follow the following link to receive your Contract: {$contractUrl} ", [], $options);
      break;
    case 'drusign_send_accepted':
      $userMailA = $params['userMailA'];
      $userNameA = $params['userNameA'];
      $contractNameA = $params['contractNameA'];

      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t("Mr/Ms {$userNameA} accepted your Contract {$contractNameA}!", [], $options);
      $message['body'][] = t("Your Contract {$contractNameA} was accepted by Mr/Ms {$userNameA},<br />if you want to contact him directly write an E-Mail to this adress: {$userMailA}", [], $options);
      break;
    case 'drusign_send_rejected':
      $userMailR = $params['userMailR'];
      $userNameR = $params['userNameR'];
      $contractNameR = $params['contractNameR'];

      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t("Mr/Ms {$userNameR} rejected your Contract {$contractNameR}!", [], $options);
      $message['body'][] = t("Your Contract {$contractNameR} was rejected by Mr/Ms {$userNameR},<br />if you want to contact him directly write an E-Mail to this adress: {$userMailR}", [], $options);
      break;
  }
}

function drusign_form_alter(&$form, &$form_state, $form_id) {
  $formObject = $form_state->getFormObject();
  if ($formObject instanceof \Drupal\Core\Entity\EntityFormInterface) {
    $entity = $formObject->getEntity();
    $operation = $formObject->getOperation();
    if (
      $entity->getEntityTypeId() === 'node'
      && in_array($entity->bundle(), ['vertrag'])
      && ($operation === 'edit' || $operation === 'default')
    ) {
      $form['#attached']['library'][] = 'drusign/init';
      $form['unencrypted_text'][] = [
        '#title' => t('Vertragsinhalt'),
        '#type' => 'textarea',
        '#weight' => 10,
        '#attributes' => [
          'id' => 'unencrypted_text'
        ]
      ];

      // if($operation === 'default'){
      // $form['actions']['saveAndSend'] = [
      //   '#type' => 'submit',
      //   '#value' => t('Save and go to "Send" Page'),
      //   '#weight' => 50,
      //   '#submit' => $form['actions']['submit']['#submit'],
      // ];
      // $form['actions']['saveAndSend']['#submit'][] = "goToSendPage";
    // }
    }
  }
}

// function goToSendPage(){
//
// }


/**
 * Implements hook_entity_extra_field_info().
 */
function drusign_entity_extra_field_info() {
  $extra = array();
  $extra['node']['vertrag']['display']['send_field'] = [
    'label' => t('Send Field'),
    'description' => t('Custom Send field for sending Contracts'),
    'weight' => 100,
    'visible' => TRUE,
  ];
  return $extra;
}

/**
 * Implements hook_node_view().
 */
function drusign_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('send_field')) {
    $builder = \Drupal::formBuilder();
    $build['send_field'] = $builder->getForm('Drupal\drusign\Form\SendButtonForm');
  }
}
